// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdEX36XFDJHdKNz-3mPqW54V0kPVfuwGU',
    appId: '1:1096174460927:web:2a6d84fed02bce04d051ca',
    messagingSenderId: '1096174460927',
    projectId: 'opclo-d01dd',
    authDomain: 'opclo-d01dd.firebaseapp.com',
    storageBucket: 'opclo-d01dd.appspot.com',
    measurementId: 'G-5RR0FT92NQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgo9m-RwQx9lOpK4M0DBcRappnSdq2X78',
    appId: '1:1096174460927:android:28dc518a6eba90cfd051ca',
    messagingSenderId: '1096174460927',
    projectId: 'opclo-d01dd',
    storageBucket: 'opclo-d01dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBakM7Fs-rB8ryy3FjSSgMw3TW8KRMIeOc',
    appId: '1:1096174460927:ios:4525645161221d57d051ca',
    messagingSenderId: '1096174460927',
    projectId: 'opclo-d01dd',
    storageBucket: 'opclo-d01dd.appspot.com',
    androidClientId: '1096174460927-3rf0rag272le3g70smmfbvk9rugtc5u8.apps.googleusercontent.com',
    iosClientId: '1096174460927-j8ooho90shve2gn4e6ul7d1i5n9gtuvi.apps.googleusercontent.com',
    iosBundleId: 'com.opclollc.opclo',
  );

}